name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ls -R
      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
