name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ls -R
      - run: git diff --name-only origin/main origin/${GITHUB_HEAD_REF}
