name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fetching Branch
        run: |
          echo "branch=$(git branch --show-current)" >> $GITHUB_ENV
      - name: Fetching Diffrence
        run: |
          git fetch origin main
          echo git diff main "${{ env.branch }}" --name-only
